#!/usr/bin/env python
import os

# Get godot-cpp path
godot_cpp_path = os.environ.get('GODOT_CPP_PATH', '../../godot-cpp')

# Import godot-cpp environment
env = SConscript(godot_cpp_path + '/SConstruct')

# Add Eigen headers
env.Append(CPPPATH=['include'])

# C++17 for Eigen
if env['platform'] != 'windows':
    env.Append(CXXFLAGS=['-O2'])  # Reduced from -O3 to save memory during compilation

# Source files (dead code removed 2025-02-02)
sources = Glob('src/*.cpp')

# Build shared library
library = env.SharedLibrary(
    'bin/libquantummatrix{}'.format(env['suffix']),
    source=sources
)

Default(library)
